import type { ActivityStatus } from '../components/ActivityTable.types';

export const activityTableStyles = {
  desktopWrapper: "hidden md:block bg-card rounded-xl border border-border overflow-hidden",
  table: "w-full",
  thead: "bg-muted/50 border-b border-border",
  th: "text-left px-6 py-4 text-sm font-medium text-muted-foreground",
  thActions: "w-12 px-6 py-4",
  tbody: "divide-y divide-border",
  row: "hover:bg-muted/30 transition-colors",
  cell: "px-6 py-4",
  iconRow: "flex items-center gap-2",
  typeIconWrap: {
    transcription: "p-2 bg-primary/10 rounded-lg",
    proof: "p-2 bg-success/10 rounded-lg",
  },
  typeIcon: {
    transcription: "w-5 h-5 text-primary",
    proof: "w-5 h-5 text-success",
  },
  source: "text-sm font-medium truncate max-w-xs",
  requester: "flex items-center gap-3",
  avatar: "w-8 h-8 rounded-full bg-primary/10 text-primary flex items-center justify-center text-xs font-medium",
  requesterName: "text-sm",
  timestamp: "text-sm text-muted-foreground",
  statusBase: "inline-flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-medium",
  statusColors: {
    processing: "bg-primary/10 text-primary",
    verified: "bg-success/10 text-success",
    completed: "bg-success/10 text-success",
    sealed: "bg-success/20 text-success",
  } satisfies Record<ActivityStatus, string>,
  actionsButton: "p-2 hover:bg-accent rounded-lg transition-colors",
  actionsIcon: "w-4 h-4 text-muted-foreground",
  mobileWrapper: "md:hidden space-y-4",
  mobileCard: "bg-card border border-border rounded-xl p-4",
  mobileHeader: "flex items-start justify-between mb-3",
  mobileTypeRow: "flex items-center gap-3",
  mobileSource: "text-sm font-medium mb-2 break-all",
  mobileFooter: "flex items-center justify-between text-sm text-muted-foreground",
  mobileRequesterRow: "flex items-center gap-2",
  mobileAvatar: "w-6 h-6 rounded-full bg-primary/10 text-primary flex items-center justify-center text-xs font-medium",
  mobileTimestamp: "text-xs",
};
