export const usageStatsStyles = {
  card: "bg-card border border-border rounded-xl p-6",
  header: "flex items-center justify-between mb-6",
  title: "font-semibold mb-1 flex items-center gap-2",
  titleIcon: "w-5 h-5 text-primary",
  period: "text-sm text-muted-foreground",
  headerRight: "text-right",
  headerRightText: "text-xs text-muted-foreground",
  list: "space-y-4",
  statRow: "flex items-center justify-between p-3 bg-muted/50 rounded-lg",
  statLeft: "flex items-center gap-3",
  statIconWrapPrimary: "p-2 bg-primary/10 rounded-lg",
  statIconWrapSuccess: "p-2 bg-success/10 rounded-lg",
  statIconWrapAccent: "p-2 bg-accent rounded-lg",
  statIconWrapMuted: "p-2 bg-muted rounded-lg",
  statIconPrimary: "w-4 h-4 text-primary",
  statIconSuccess: "w-4 h-4 text-success",
  statIconDefault: "w-4 h-4 text-foreground",
  statLabel: "text-sm font-medium",
  statSubLabel: "text-xs text-muted-foreground",
  statRight: "text-right",
  statValue: "text-lg font-bold",
  statTrend: "text-xs text-success flex items-center gap-1 justify-end",
  trendIcon: "w-3 h-3",
  storageIcon: "w-4 h-4 text-muted-foreground",
  progressWrap: "mt-6 pt-6 border-t border-border",
  progressHeader: "flex items-center justify-between mb-2",
  progressLabel: "text-sm font-medium",
  progressValue: "text-sm text-muted-foreground",
  progressTrack: "w-full bg-muted rounded-full h-2",
  progressBar: "bg-primary h-2 rounded-full transition-all duration-300",
  progressNote: "text-xs text-muted-foreground mt-2",
};
